--- 
apiVersion: v1
kind: Service
metadata: 
  name: zipkinservice
spec: 
  ports: 
    - 
      port: 80
      protocol: TCP
      targetPort: 9411
  selector: 
    app: zipkinserviceS
  type: NodePort