apiVersion: v1
kind: Service
metadata:
  name: zipkin-test
spec:
  selector:
    app: zipkin
    env: qa
  type: NodePort
  ports:
    - targetPort: 9411  
      port: 9411
      nodePort: 32765

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  type: LoadBalancer 
  selector:
    app: nodeapp
  ports:
    - targetPort: 8080
      port: 80
    