---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sspingpetclinc
  labels:
    app: spingpetclinc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: spingpetclinc
      version: "1.0"
  template:
    metadata:
      labels:
        app: spingpetclinc
        version: "1.0"
    spec:
      containers:
        - image: cicdcontainer/springpetclinic:1.0
          name: spingpetclinc
          ports:
            - containerPort: 8080
              protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  name: spingpetclinc
spec:
  type: NodePort
  selector:
    app: spingpetclinc
  ports:
    - targetPort: 8080
      port: 8080
