---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpetclinic
  labels:
    app: springpetclinic
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: springpetclinic
      version: "1.0"
  template:
    metadata:
      labels:
        app: springpetclinic
        version: "1.0"
    spec:
      containers:
        - image: svikram01/springpet:latest
          name: springpetclinic
          ports:
            - containerPort: 8080
              protocol: TCP 
---
apiVersion: v1
kind: Service
metadata:
  name: springpetclinic
spec:
  type: NodePort
  selector:
    app: springpetclinic
  ports:
    - targetPort: 8080
      port: 8080
