--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: zipkin
  name: zipkin
spec: 
  containers: 
    - 
      image: openzipkin/zipkin
      name: zipkin
      readinessProbe: 
        httpGet: 
          path: /api/v1/services
          port: 9411
