apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zipkin-qa
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-qa
      env: qa
  template:
    metadata:
      labels:
        app: zipkin-qa
        env: qa
    spec:
      containers:
        - image: openzipkin/zipkin
          name: zipkin-qa
          ports:
            - containerPort: 9411
              protocol: TCP 
