--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: zipkin
  name: zipkin
spec: 
  containers: 
    - 
      image: openzipkin/zipkin
      name: zipkin
      ports: 
        - 
          containerPort: 9411

